"""
Cada novo termo na seqüência de Fibonacci é gerado adicionando os dois termos anteriores. Começando com 1 e 2, os primeiros 10 termos serão:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Considerando os termos da seqüência de Fibonacci cujos valores não excedam quatro milhões, encontre a soma dos termos com valor par.

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
# definindo os primeiros termos da sequência Fibonacci
n1, n2, soma_t = 1, 1, 0 #primerio termo: n1 recebe 1; segundo termo: n2 recebe 1; soma_t recebe 0
#a estrutura while foi escolhida
while True:
    n1, n2 = n2, n2 + n1
    if n2 >= 4000000: break
    if not(n2 % 2): soma_t += n2
print(soma_t)

#In Setup = Intel Core i3 530 2.93 GHz
#Less time = 0.033284264 seconds
#answer = 4613732
#resposta = 4613732