"""
Cada novo termo na seqüência de Fibonacci é gerado adicionando os dois termos anteriores. Começando com 1 e 2, os primeiros 10 termos serão:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Considerando os termos da seqüência de Fibonacci cujos valores não excedam quatro milhões, encontre a soma dos termos com valor par.

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
n1, n2 = 0, 1
soma_t = 0
while True:
    x, n1 = n1, n2
    n2 = x + n2
    if n2 >= 4000000:
      break
    if n2 % 2 == 0:
      soma_t += n2
print(soma_t)
#time = 0.037318583 seconds
#answer = 4613732
#resposta = 4613732